version: '2'
services:
  db:
    image: db:development
    volumes:
      - data:/var/lib/mysql
  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
    volumes:
      - ./ops/development/docker/container/app/config/secrets.yml:/usr/src/app/config/secrets.yml
      - ./ops/development/docker/container/app/config/database.yml:/usr/src/app/config/database.yml
  proxy:
    image: proxy:development
    volumes:
      - ./ops/development/docker/container/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./ops/development/docker/container/proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  data:
    driver: local