FROM k2works/baukis-devops-app:latest
ADD ./ops/staging/docker/container/app/config/secrets.yml /usr/src/app/config/secrets.yml
ADD ./ops/staging/docker/container/app/config/database.yml /usr/src/app/config/database.yml
ADD ./ops/staging/docker/container/app/config/environments/staging.rb /usr/src/app/config/staging.rb