FROM k2works/baukis-devops-app:latest
ADD ./ops/production/docker/container/app/config/secrets.yml /usr/src/app/config/secrets.yml
ADD ./ops/production/docker/container/app/config/database.yml /usr/src/app/config/database.yml
ADD ./ops/production/docker/container/app/config/environments/production.rb /usr/src/app/config/production.rb